### ISSUE TITLE
Screen saver does not unlock

### ISSUE THREAD

**Issue by imjeet** [linuxmint/cinnamon-screensaver#186] opened 2016-12-22 07:41 UTC
I am using mint cinnamon 18.1 32 bit. After upgrading from 18 to 18.1 the lock screen does not unlock. Even after system format the problem remains. I am using default screen saver. But switch account option is working properly. I mean to say the icon beside unlock icon. I can unlock screen using switch account after lock the screen.

Thank you sir. Merry christmass and happy new year in advance
![screenshot from 2016-12-22 13-11-07](https://cloud.githubusercontent.com/assets/24682410/21418562/2cad85ac-c848-11e6-8abb-05c5377f5356.png)

**Comment by pxcandeias** [comment] 2016-12-22 10:35
Hi all,

I am experiencing the exact same problem. The transition path was the same (Mint 18 -> 18.1), 32 bit system, default screensaver. Tried changing to a a different screensaver (GLMatrix) but the problem persists. Also tried Clem's recipe in entry 90 of the Linux Mint blog (http://blog.linuxmint.com/?p=3185) but it did not work, the cinnamon-screensaver command never finishes (see image below).

![captura de ecra de 2016-12-22 10-32-17](https://cloud.githubusercontent.com/assets/11465815/21422905/08ec3de0-c832-11e6-9cc6-b8d5113bee4c.png)

I hope you can fix this!

**Comment by wacher74** [comment] 2016-12-23 00:44
See https://github.com/linuxmint/cinnamon-screensaver/issues/183

**Comment by wacher74** [comment] 2016-12-23 00:47
I don't use password for my screensaver, I want unlock my computer with a simple key press, but now I have to press reset button instead.

**Comment by imjeet** [comment] 2016-12-23 07:29
Thank you for this info, but the problem remains.

**Comment by leigh123linux** [comment] 2016-12-23 07:48
Duplicate of #183

**Closed by leigh123linux** 2016-12-23 07:48 UTC
