### ISSUE TITLE
Two-factor PAM authentication is broken

### ISSUE THREAD

**Issue by jelco** [linuxmint/cinnamon-screensaver#165] opened 2016-12-04 10:35 UTC
I've had google-authenticator configured on my laptop for quite a while, including PAM hooks in cinnamon-screensaver. After the recent update that came with Fedora 25 I noticed that this was silently disabled since the PAM configuration moved from cinnamon-screensaver to cinnamon-desktop. (Just a side note here, but really, that's something you could have handled in a post-upgrade hook. Bad packaging guys.)

After reconfiguring google-authenticator in the cinnamon-desktop PAM file, unlocking becomes impossible. After asking for the password the system doesn't prompt me for a verification code but simply enters its delay before telling me my password is incorrect.

Since the phrasing in your prompt is non-PAM I got the feeling this has suddenly become a non-standard authentication system, and after digging a little I get the strong feeling that you have reinvented part of the wheel by creating your own intermediate pam redirection through cinnamon-desktop, which can't cope with additional passes such as google-authenticator. I won't claim to fully understand how your authentication system currently works, but I do know that you are not directly interfacing with PAM anymore and have suddenly lost support for some basic PAM features. They seem strongly related to me.

Steps to reproduce:

1. Open `/etc/pam.d/cinnamon-desktop`
2. Find the line 
```
auth       include      system-auth
```
3. Replace with the lines 
```
auth       substack     system-auth
auth       required     pam_google_authenticator.so nullok
```

This exact configuration worked flawlessly when I still had to configure this on `/etc/pam.d/cinnamon-screensaver`, on Fedora 23 and 24.

**Comment by leigh123linux** [comment] 2016-12-04 10:41
If you have a valid issue open a bug at redhat bugzilla

**Comment by jelco** [comment] 2016-12-04 10:43
Why should I open an issue with RedHat? This is functionality that is exclusively broken in cinnamon-screensaver. Everything else (sshd, gdm, sudo) still works completely fine. If you can explain to me why this is not an issue in your software then I will happily submit it to RH, but at this point I'm pretty sure they have nothing to do with this.

I only mentioned Fedora in this process because that is the reason I got the update of the cinnamon-screensaver package. It is otherwise unrelated.

**Comment by leigh123linux** [comment] 2016-12-04 11:21
See previous comment.

Have you tried killing and running cinnamon-screensaver from a terminal and see if there are any warnings.
Also try with selinux disabled

```
sudo setenforce 0
```

does journalctl log show anything?


P.S I get touchy when people criticise my packageing, this may help in the future when the issue is fixed

http://pkgs.fedoraproject.org/cgit/rpms/cinnamon-desktop.git/commit/?id=736cbf017e1ef35a42b4eb613d5f23cd05e0b383

**Comment by mtwebster** [comment] 2016-12-04 15:44
Working on this.. I the problem after trying to fix fingerprint authentication...

**Comment by jelco** [comment] 2016-12-04 16:06
SElinux didn't change anything, journalctl shows this (not sure if the first one is related, but timestamp-wise seems to be connected):

```
Dec 04 16:45:41 xxx cinnamon-screen[2797]: Unable to connect to ibus: Could not connect: Connection refused
Dec 04 16:45:47 xxx cinnamon-desktop(pam_google_authenticator)[2797]: Invalid verification code
```

From terminal:

```
[jelco@xxx ~]$ cinnamon-screensaver
Cinnamon Screensaver support not found in current theme - adding some...
Trying to connect to logind...
Starting screensaver...
Not running under the session scope, trying XDG_SESSION_ID
found session: 2
Successfully using logind

(cinnamon-screensaver-main.py:4898): IBUS-WARNING **: Unable to connect to ibus: Could not connect: Connection refused
Terminated
[jelco@xxx ~]$ 
```

Closing termination was required from another shell in order to skip the screensaver and actually get back to the desktop, it's not related to this problem.

@leigh123linux My problem with the packaging is that `/etc/pam.d/cinnamon-screensaver` got renamed to `/etc/pam.d/cinnamon-screensaver.rpmsave` and a new file `/etc/pam.d/cinnamon-desktop` got created with defaults. I would expect the package to check for a pre-existing `/etc/pam.d/cinnamon-screensaver` file and use those contents for the new `/etc/pam.d/cinnamon-desktop` file. The defaults and functionality seem to be verbatim copies so this shouldn't impose any risks - you're simply renaming the config file.

**Comment by leigh123linux** [comment] 2016-12-04 17:12
/etc/pam.d/cinnamon-screensaver to /etc/pam.d/cinnamon-desktop might have just been a rename but the file and all pam function were moved to cinnamon-desktop package.
Fedora cinnamon packaging is done by me only (I have tried countless time to get others interested in co-maintaining), **I don't get enough time to check or even think about every scenario**.
This is unlikely to improve in the future as I'm not prepared to cutback on my rpmfusion duties or orphan other packages to make more time.

**Comment by jelco** [comment] 2016-12-04 17:37
Fair enough, I understand that it's very easy to complain while this is best-effort so I can appreciate that sometimes there are edge cases that go overlooked. However, I don't consider the security of the lock screen through PAM an unusual use case and a weird scenario (albeit undocumented). I would be fine with just some info in the RPM changelog that I can easily find out stuff got migrated, but as it stands I just updated my software, discovered that part of the security features of my workstation got silently disabled, and had to dive into your git log to discover the problem.

I don't mean to step on your toes and detract from any hard work you're doing, but you've got to admit that is not really a great user experience. If not, for the sake of not going off on major tangents, I'd be happy to agree to disagree - the real problem with the PAM interfacing is apparently known which is definitely enough to make me a happy user again, and I can live with not having my packaging comments taken into account.

**Comment by mtwebster** [comment] 2016-12-08 23:13
Fixed by 38a626d1a3c64736f0acfe22 - please let me know if/when you get an update, to confirm satisfactory behavior.

**Closed by mtwebster** 2016-12-08 23:13 UTC

**Comment by jelco** [comment] 2016-12-12 10:28
Cheers for the quick fix - I don't have a package yet and can't get it to build myself at the moment, but I'll let you know as soon as I get the opportunity to test it.

**Comment by leigh123linux** [comment] 2016-12-12 10:57
It currently being pushed to updates-testing

https://bodhi.fedoraproject.org/updates/FEDORA-2016-7c71cb2887

**Comment by jelco** [comment] 2016-12-12 13:00
Thanks! I updated cinnamon-desktop and cinnamon-screensaver, and I can confirm the fix works with Google Authenticator. I am seeing a small hang between the moment I hit a key in the lock screen and the dialog appearing, and this error shows up when I run it on the terminal:

```
Traceback (most recent call last):
  File "/usr/share/cinnamon-screensaver/unlock.py", line 297, in on_auth_enter_key
    self.on_unlock_clicked()
  File "/usr/share/cinnamon-screensaver/unlock.py", line 290, in on_unlock_clicked
    self.auth_client.message_to_child(text)
  File "/usr/share/cinnamon-screensaver/pamhelper/authClient.py", line 102, in message_to_child
    status = self.in_pipe.write_bytes(b)
AttributeError: 'NoneType' object has no attribute 'write_bytes'
```

Don't know if they're related though. Please let me know if you want me to file a separate bug report for this one.

**Comment by mtwebster** [comment] 2016-12-12 15:27
New issue fixed by https://github.com/linuxmint/cinnamon-screensaver/commit/094594684ad6e6f8209184301cc2f37782b38819
