### ISSUE TITLE
Cannot unlock cinnamon-screensaver

### ISSUE THREAD

**Issue by gustauperez** [linuxmint/cinnamon-screensaver#110] opened 2015-08-17 07:06 UTC
This is with FreeBSD 11, cinnamon 2.6.13 and cinnamon-screensaver 2.6.4, but perhaps it has always happened with all 2.6.x cinnamon-screensaver versions.

When the screensaver kicks in, any password is rejected. Thus the screensaver cannot be unlocked and thus rendering the session useless.

Previous 2.4.x did fine. 

The cinnamon-desktop is compiled with the right pam file location [1] and the pam file is named cinnamon-screensaver.pam. Its contents are just a copy of other pam services which work fine. 

I checked .cache/gdm/session.log, but I'm not sure there's something relevant there. No ~/.xsession-errors to be checked. 

How can I debug what's happening?

[1] --with-pam-prefix=/usr/local/etc/pam.d/

**Comment by feren** [comment] 2016-08-21 20:22
To debug, try these commands in Terminal:
```
killall cinnamon-screensaver
cinnamon-screensaver
```
Then lock yourself out
Then go into tty1, log in, and type these commands:
Cinnamon Stable:
`export DISPLAY=:0 && killall cinnamon-screensaver`
Cinnamon NIGHTLY:
`export DISPLAY=:0 && killall cinnamon-screensaver-main.py`
Then go back to your (what was locked) session, and look into the Terminal output in there

**Comment by thomai** [comment] 2016-10-12 23:58
Same problem on Arch Linux. The work around by @feren works for me but: I cannot open gui applications anymore via the panel after switching back to tty7 (cinnamon session). Any ideas?

**Comment by feren** [comment] 2016-10-13 06:39
@thomai Not sure, but some of the developers could make do with what output came out of that graphical terminal...

**Comment by thomai** [comment] 2016-10-19 10:46
@feren I solved the problem by setting a static hostname on Arch Linux.

**Comment by mtwebster** [comment] 2016-10-19 13:58
@thomai on Arch what did you have configured before?  You had no /etc/hostname?  I'd like to reproduce this so the new screensaver can deal with it properly if it comes up.

**Comment by thomai** [comment] 2016-10-19 17:21
Exactly. After creating the file explicitly and inserting a proper hostname, the problem was solved.

**Comment by feren** [comment] 2016-10-19 17:28
@thomai You may want to check if you had an /etc/hostname file beforehand to help @mtwebster get down to the problem

**Comment by thomai** [comment] 2016-10-20 07:23
@feren I checked that already on fixing my problem.

**Comment by feren** [comment] 2016-10-22 08:50
@mtwebster Ok, so he didn't have the hostname file before, you may want to either see if there's a problem in Cinnamon's control without the hostnames file and/or close the issue...

**Comment by ACinnamonUserInUK** [comment] 2017-03-23 14:31
I have had a similar problem. To wit: sometimes the screensaver will not show the password box and so I can't login and had to restart by pressing the power button. It may be worth mentioned that the problem is accompanied by my chosen screensaver text appearing _in more than one place on the screen_ simultaneously.

**Comment by lobstaj** [comment] 2017-06-16 20:45
I'm suffering from the same issue. And yes, I do have /etc/hostname in place and always had.

And I'm experiencing the same symptom as @ACinnamonUserInUK , namely the clock text is displayed twice in different locations. In one place, it's as if it was greyed out or something, and then in another place it's visible nomarlly.

It's almost as if there were two screensavers on top of each other and I can only unlock the top one.

**Comment by chrisguidry** [comment] 2017-08-01 01:57
I have a similar issue, but I don't think it's related to /etc/hostname (I have an /etc/hostname already).  I'm using LDAP client authentication, which works fine in all other contexts.  I've determined that if I remove `libnss-ldap`, `cinnamon-screensaver` works as expected.

Following these steps to get debugging messages from `cinnamon-screensaver`:

```
$ cinnamon-screensaver-command -e
$ cinnamon-screensaver --debug
```

Then performing these steps to reproduce:

1. Ctrl+Alt+L to lock the screen
2. Wait a moment, maybe 5 seconds
3. Enter my *valid* password (I swear, it's valid)
4. Receive the "Incorrect password" message
5. Click switch user to get back to the login screen, enter password, it's accepted

I get this output:

```
Debug mode active
Cinnamon Screensaver support not found in current theme - adding some...
Trying to connect to logind...
Starting screensaver...
Successfully using logind
Found 1 Xinerama screens on display :0
Monitor 0 is 0,0 1366 x 768
Cinnamon Screensaver compiled without Solaris Xinerama support
Scale factor of 1 applied.  Monitor 0 is 0,0 1366 x 768
authClient initialize... initialized already: False
authClient initialize... initialized already: True
[... repeated many times ...]
pam_start ("cinnamon-screensaver", "chris", ...) ==> 0 (Success)
authClient initialize... initialized already: True
[... repeated many times ...]
Handling message style 1: 'Password: '
Waiting for respose to message style 1: 'Password: '
Waiting for lock
Waiting for response
Got message style 1: 'Password: '
Output from pam helper: 'CS_PAM_AUTH_SET_PROMPT_Password: _'
authClient idle add auth-prompt
Output from pam helper: 'CS_PAM_AUTH_BUSY_FALSE'
authClient idle add auth-busy
Output from pam helper: ''
authClient initialize... initialized already: True
[... repeated several times ...]
authClient message to child
authClient initialize... initialized already: True
auth_message_handler processing response string
should interrupt: 0
Got response
Got respose to message style 1: interrupt:0
Msg handler returned 1
Output from pam helper: 'CS_PAM_AUTH_BUSY_TRUE'
authClient idle add auth-busy
Output from pam helper: ''
   pam_authenticate (...) ==> 7 (Authentication failure)
 pam_end (...) ==> 0 (Success)
Verify user returned: FALSE
Verify user returned error: Incorrect password.
Authentication failed, retrying (1)
Output from pam helper: 'CS_PAM_AUTH_FAILURE'
authClient idle add failure
Output from pam helper: ''
pam_start ("cinnamon-screensaver", "chris", ...) ==> 0 (Success)
Handling message style 1: 'Password: '
Waiting for respose to message style 1: 'Password: '
Waiting for lock
Waiting for response
Got message style 1: 'Password: '
Output from pam helper: 'CS_PAM_AUTH_SET_PROMPT_Password: _'
authClient idle add auth-prompt
Output from pam helper: 'CS_PAM_AUTH_BUSY_FALSE'
authClient idle add auth-busy
Output from pam helper: ''
authClient initialize... initialized already: True
[... repeated many times ...]
Received Lock from session manager
authClient initialize... initialized already: True
Received Unlock from session manager
authClient message to child
auth_message_handler processing response string
Got no response
should interrupt: 1
Got response
Got respose to message style 1: interrupt:1
Msg handler returned 0
   pam_authenticate (...) ==> 7 (Authentication failure)
Output from pam helper: 'CS_PAM_AUTH_CANCELLED'
authClient idle add cancel
Output from pam helper: ''
authClient helper process completed...
helper process did not exit cleanly: Child process killed by signal 15
Received Active changed from session manager
authClient cancel requested, but no helper process
```

Thanks in advance for looking into this.

**Comment by chrisguidry** [comment] 2017-08-01 02:02
An interesting followup, I believe what I'm seeing here:

http://pubs.opengroup.org/onlinepubs/8329799/chap5.htm

Indicates that error 7 from `pam_authenticate` is `PAM_PERM_DENIED`, which makes it sound like `cinnamon-screensaver` isn't running with high enough privilege to authenticate me?

**Comment by chrisguidry** [comment] 2017-08-01 12:17
Ah, please disregard, it turns out I had missed one piece of the LDAP auth setup (installing `libpam-ldap`).  Now `cinnamon-screensaver` is able to unlock for me.

**Comment by dan-stromberg** [comment] 2019-08-30 14:48
For me, on Linux Mint 19.1, my /etc/shadow was root.root 640.  I changed it to root.shadow 640.  Then I was able to reopen my session.

**Comment by mike1808** [comment] 2023-03-02 03:06
Hey. I'm using cinnamon-screensaver `5.6.3` on `Linux workstation 5.15.91-1-MANJARO #1 SMP PREEMPT` and seeing this exact issue. Every time I'm trying to turn on the system after sleep it locks out itself and produces mentioned logs like these:

> Aug 12 20:45:18 alienware cinnamon-screensaver-pam-helper[44088]: pam_unix(cinnamon-screensaver:auth): conversation failed
> Aug 12 20:45:18 alienware cinnamon-screensaver-pam-helper[44088]: pam_unix(cinnamon-screensaver:auth): auth could not identify password for [xxx]

**Comment by sebgre** [comment] 2024-05-22 11:58
@mike1808 
Hi Mike. I know this is an old post, but I have the exact same issue on Arch Linux with cinnamon-screensaver 6.0.3-1. It may also be the case with late 5 versions as I’m struggling with this issue for about 2 months now. Have you found a solution to this problem?

**Comment by a-mckinley** [comment] 2024-09-07 19:48
Still suffering with this issue for several years. I see the messages in the logs about "conversation failed" as others have pointed out.

**Comment by leigh123linux** [comment] 2024-09-08 07:20
Start a new issue and provide some proper debugging info.

**Closed by leigh123linux** 2024-09-08 07:20 UTC
Labels: BUG
