### ISSUE TITLE
System unlocked when resuming from suspend.

### ISSUE THREAD

**Issue by awnumar** [linuxmint/cinnamon-screensaver#249] opened 2017-11-01 10:04 UTC
```
 * Cinnamon version: Cinnamon 3.4.6
 * Distribution: Arch Linux
 * Graphics hardware: Intel Iris Plus Graphics 640
 * Intel Core i7-7560U 64-bit
 ```

**Issue**

When suspending the laptop by putting the lid down, and then resuming it, the system is unlocked.

**Steps to reproduce**

1. Put the lid down.
2. Wait.
3. Lift it again.

**Expected behaviour**

The system would be locked.

**Other information**

I'm running a Dell XPS 13 (9360), with Arch Linux installed via Antergos.

**Comment by clefebvre** [comment] 2017-11-09 11:15
I'm going to assume this isn't a configuration issue or a distribution/packaging issue.

If so, the issue is a duplicate of https://github.com/linuxmint/cinnamon-screensaver/issues/219.

**Closed by clefebvre** 2017-11-09 11:15 UTC
