### ISSUE TITLE
cinnamon-screensaver-pam-helper uses 100% of one processor

### ISSUE THREAD

**Issue by Mintulix** [linuxmint/cinnamon-screensaver#182] opened 2016-12-19 08:49 UTC
I played a bit with cinnamon-screensaver 3.2.9:
Locked screen, switched users, closed one session, switched again, ...
Then the process cinnamon-screensaver-pam-helper had a problem (should it be closed automatically?).
Don't know how exactly to reproduce this (had this issue two times now), but I can try if it's needed. Also when you need a log - which one could this be?

**Comment by leigh123linux** [comment] 2016-12-19 11:38
Duplicate of https://github.com/linuxmint/cinnamon-screensaver/issues/180

**Closed by leigh123linux** 2016-12-19 11:38 UTC
