### ISSUE TITLE
Caffeine not Inhibiting Cinnamon Screensaver

### ISSUE THREAD

**Issue by zombiewoof** [linuxmint/cinnamon-screensaver#17] opened 2013-05-17 19:56 UTC
OS: Ubuntu 12.10
  3.5.0-30-generic / #51-Ubuntu SMP Tue May 14 18:49:52 UTC 2013

Screensaver Version: cinnamon-screensaver-command 1.8.0

The screensaver is not picking up the no-blank information from Caffeine. This was working prior to the upgrade of Cinnamon, which contained the Cinnamon Screensaver. Caffeine shows the steam, above the cup, which indicates that it is trying to inhibit the screensaver, but the screensaver activates just the same.

**Comment by cayjd** [comment] 2015-01-23 23:55
The problem is still present in Cinnamon 17.1, using the latest Caffeine (2.8.3). I don't even understand if what needs to be fixed is cinnamon-screensaver or caffeine. Perhaps someone could explain?

**Comment by dalcde** [comment] 2015-01-24 07:45
Seems like caffeine  uses dbus to ask the screensaver to not open, but cinnamon-screensaver ignores it.

**Comment by cayjd** [comment] 2015-01-26 20:28
dalcde, thank you for the reply. Do you see where this should be fixed? 
I see you have some proposed changes for cinnamon-screensaver, do they maybe address this problem?

**Comment by mtwebster** [comment] 2015-01-26 20:36
Just throwing in 5 cents here - anything that wants to prevent the screensaver/session idle should be talking via dbus to org.gnome.SessionManager (which is provided by cinnamon-session)

**Comment by dalcde** [comment] 2015-01-26 20:46
Caffeine communicates through the freedesktop interface iirc

**Comment by DrPandemic** [comment] 2015-04-04 16:12
I quickly looked at the source of your applet @mtwebster and caffeine source. The difference I found was that you are using org.gnome.SessionManager in dbus and caffeine is using  org.gnome.ScreenSaver.

Cinnamon-Screensaver seems to only listen to org.cinnamon.ScreenSaver and org.gnome.SessionManager. Shouldn't it also listen for org.gnome.ScreenSaver. By doing this, it would work with tools made for the gnome screensaver. Would it be a good idea or do I miss something?

And here goes my 5 cents!

**Comment by mtwebster** [comment] 2015-04-04 16:26
Honestly I think caffeine should be worrying about org.gnome.SessionManager, not .Screensaver.  This is why we kept the .gnome name there (and as far as I know, most other apps use the SessionManager interface as well)

**Comment by DrPandemic** [comment] 2015-04-04 21:31
Interesting. I guess we only have 2 options here. Either we submit a PR to caffeine to add .SessionManager, or we follow caffeine and we listen also at .Screensaver. I think if we don't try something, we'll never be able to use caffeine.

Would it be bad for Cinnamon Screensaver to add .Screensaver?

**Comment by mtwebster** [comment] 2016-01-17 16:30
See this explanation: https://github.com/linuxmint/Cinnamon/issues/2458#issuecomment-172347064

**Closed by mtwebster** 2016-01-17 16:30 UTC
